### ISSUE TITLE
Função "is_in_check" (implementação da IA)

### ISSUE THREAD

**Issue by arthurnakaoiduff** [paulodayrell/Chess#17]
Surgiu um bug na função is_in_check na linha de retorno da função:

`return (rei.linha, rei.coluna) in movements`

Acredito que seja por conta da cor do jogador no tabuleiro, visto que com a IA, ele não deve ter uma cor e a variavel rei não está recebendo nenhuma peça (se tornando None) e não conseguindo recuperar os atributos "linha" e "coluna".

**Comment by nicolesuet** [comment]
Apos debugar o código descobri que o rei é capturado, logo ao trocar de turno e ver se houve check, o rei não existe nos movimentos, logo ele fica None

**Comment by GMMULLER** [comment]
Acredito que tenha um problema na passagem de turno. Talvez a troca de turno não esteja sendo feita no turno da IA.

**Comment by GMMULLER** [comment]
Chamar move_ai várias vezes também acarreta no problema de incremento de piece.moves, sem que haja um decremento no undo_move.

**Comment by GMMULLER** [comment]
Coloquei a passagem de turno para acontecer no momento em que o make_move é chamado. Isso faz com que a passagem de turno aconteça uma única vez.
