### ISSUE TITLE
IA não leva em consideração xeque

### ISSUE THREAD

**Issue by GMMULLER** [paulodayrell/Chess#18]
Quando as peças da IA estão em xeque ela pode fazer uma movimentação que não necessariamente à tira do xeque, tornando o estado do tabuleiro inconsistente com as regras do jogo. IA deve checar se está em xeque através do atributo "current_player_check" (boleano) de tabuleiro. Caso esteja ela só poderá fazer movimentos que se encontram no vetor "get_out_of_check_moves".

**Comment by nicolesuet** [comment]
quando estiver em check o get_moves pega só as pega as movimentações que tiram o rei do check
