### ISSUE TITLE
Bug na funcao testeTorreParaRoque

### ISSUE THREAD

**Issue by arthurnakaoiduff** [paulodayrell/Chess#26]
A função "testeTorreParaRoque" está tentando acessar valores no tabuleiro que não existem (ex: linha 0 coluna 8).

**Comment by madfrr** [comment]
O problema estava nos testes. No código, a função "testeTorreParaRoque" só é chamada quando a quantidade de movimentos do Rei for igual a zero, pois tentamos verificar se tem uma torre baseado na posição absoluta do rei.
